# Site settings
title: Gaurav Sood
email: gauravsood1410@gmail.com
url: https://grvsood.github.io
description: "Computer Programmer<br> Former Intern at IIRS/ISRO Dehradun"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Gaurav Sood

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/grvsood
  - title: linkedin
    url: https://www.linkedin.com/in/gauravsood1410/
  - title: twitter
    url: https://twitter.com/gauravsood_
  - title: facebook
    url: https://www.facebook.com/gauravsood1410
  - title: instagram
    url: https://www.instagram.com/gauravsood_


# Build settings
markdown: kramdown
permalink: pretty
