title: Posts
description: My weekly programming insights
author: Gaurav Sood
github: https://github.com/grvsood
about: Software Developer Engineer at Amazon.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  # - icon: fa-facebook
  #   link: "#"
  - icon: fa-twitter
    link: "https://twitter.com/gauravsood_"
  # - icon: fa-linkedin
  #   link: "#"
  # - icon: fa-stack-exchange
  #   link: "#"
  - icon: fa-github
    link: "https://github.com/grvsood"

share:
  twitter_username: gauravsood_
  fb_appid: 1749788565247320

urls:
  - text: About Me
    url: /about/
  - text: My Projects
    url: /projects/
  - text: XML Feed
    url: /feed.xml

url: "https://grvsood.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]

theme: jekyll-theme-slate
